default_exception:
  code: 10001
  message: This is a default exception
  metadata:
    key1: value1
    key2: value2
  status: 501
  
argument_exception:
  code: 10002
  message: Hello World
  metadata:
    key1: value1
    key2: value2
    key3: value3
  status: 502
